# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: La Prépa Vaucanson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Le site officiel des Classes Préparatoires aux Grandes Écoles (ou C.P.G.E.)
  du Lycée Vaucanson de Grenoble.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
  
# markdown: redcarpet
# redcarpet:
#     extensions: [with_toc_data]
